name: pphack
summary: The Most Advanced Client-Side Prototype Pollution Scanner
description: |
      The Most Advanced Client-Side Prototype Pollution Scanner
version: 0.0.1
grade: stable
base: core20

confinement: strict

apps:
  pphack:
    command: bin/pphack
    plugs:
      - home
      - network

parts:
  pphack:
    plugin: go
    source-type: git
    source: https://github.com/edoardottt/pphack